# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""Regenerate the root index.md from cheatsheets/*.md (Constitution P-4).

Deterministic and side-effect-bounded: reads cheatsheets/, writes index.md.
Run via: uv run scripts/register_cheatsheet.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_HEADER = "# Cheatsheets\n\n<!-- Generated by scripts/register_cheatsheet.py — do not edit by hand. -->\n\n"


def extract_title(path: Path) -> str:
    """First Markdown H1 in the file, else the filename stem."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def discover_cheatsheets(root: Path) -> list[tuple[str, str]]:
    """Sorted (relpath, title) for every cheatsheets/*.md under root."""
    cdir = root / "cheatsheets"
    if not cdir.is_dir():
        return []
    entries: list[tuple[str, str]] = []
    for md in sorted(cdir.glob("*.md")):
        rel = md.relative_to(root).as_posix()
        entries.append((rel, extract_title(md)))
    return entries


def render_index(entries: list[tuple[str, str]]) -> str:
    if not entries:
        return _HEADER + "_No cheatsheets yet._\n"
    lines = [f"- [{title}]({rel})" for rel, title in entries]
    return _HEADER + "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate root index.md from cheatsheets/.")
    parser.add_argument("--root", default=".", help="Repo root (default: current directory).")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    entries = discover_cheatsheets(root)
    (root / "index.md").write_text(render_index(entries), encoding="utf-8")
    print(f"index.md updated: {len(entries)} cheatsheet(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
